name: Regression Tests

on:
  workflow_run:
    workflows: ["Smoke Tests"]
    types:
      - completed
  schedule:
    - cron: '0 3 * * 0'  # Runs every Sunday at 3:00 AM UTC
  workflow_dispatch:

jobs:
  regression:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and Run Regression Tests
        run: mvn clean test -DsuiteXmlFile=src/test/resources/tests/e2e.xml